version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: voenix-postgres
    environment:
      POSTGRES_DB: voenix_java
      POSTGRES_USER: voenix
      POSTGRES_PASSWORD: voenix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voenix -d voenix_java"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voenix-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/voenix_java
      DATABASE_USERNAME: voenix
      DATABASE_PASSWORD: voenix
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: