run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-dirs:
    - tmp
    - vendor
    - .gocache
