create table
  article_price_calculation (
    id bigint generated by default as identity primary key,
    article_id bigint not null unique,
    -- purchase section fields
    purchase_price_net integer not null default 0,
    purchase_price_tax integer not null default 0,
    purchase_price_gross integer not null default 0,
    purchase_cost_net integer not null default 0,
    purchase_cost_tax integer not null default 0,
    purchase_cost_gross integer not null default 0,
    purchase_cost_percent decimal(5, 2) not null default 0,
    purchase_total_net integer not null default 0,
    purchase_total_tax integer not null default 0,
    purchase_total_gross integer not null default 0,
    purchase_price_unit varchar(50) not null default 'PER_PIECE',
    purchase_vat_rate_id bigint,
    purchase_vat_rate_percent decimal(5, 2) not null default 19,
    purchase_calculation_mode varchar(10) not null default 'NET',
    -- sales section fields
    sales_vat_rate_id bigint,
    sales_vat_rate_percent decimal(5, 2) not null default 19,
    sales_margin_net integer not null default 0,
    sales_margin_tax integer not null default 0,
    sales_margin_gross integer not null default 0,
    sales_margin_percent decimal(5, 2) not null default 0,
    sales_total_net integer not null default 0,
    sales_total_tax integer not null default 0,
    sales_total_gross integer not null default 0,
    sales_price_unit varchar(50) not null default 'PER_PIECE',
    sales_calculation_mode varchar(10) not null default 'NET',
    -- ui state fields
    purchase_price_corresponds varchar(10) not null default 'NET',
    sales_price_corresponds varchar(10) not null default 'NET',
    purchase_active_row varchar(20) not null default 'PRICE',
    sales_active_row varchar(20) not null default 'MARGIN',
    -- timestamps
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    -- constraints
    constraint fk_cost_calculation_article foreign key (article_id) references articles (id) on delete cascade,
    constraint fk_purchase_vat_rate foreign key (purchase_vat_rate_id) references value_added_taxes (id),
    constraint fk_sales_vat_rate foreign key (sales_vat_rate_id) references value_added_taxes (id),
    constraint chk_purchase_calculation_mode check (purchase_calculation_mode in ('NET', 'GROSS')),
    constraint chk_sales_calculation_mode check (sales_calculation_mode in ('NET', 'GROSS')),
    constraint chk_purchase_price_corresponds check (purchase_price_corresponds in ('NET', 'GROSS')),
    constraint chk_sales_price_corresponds check (sales_price_corresponds in ('NET', 'GROSS')),
    constraint chk_purchase_active_row check (purchase_active_row in ('PRICE', 'COST', 'TOTAL')),
    constraint chk_sales_active_row check (sales_active_row in ('MARGIN', 'TOTAL'))
  );



create index idx_article_price_calculation_article_id on article_price_calculation (article_id);



create index idx_article_price_calculation_purchase_vat_rate on article_price_calculation (purchase_vat_rate_id);



create index idx_article_price_calculation_sales_vat_rate on article_price_calculation (sales_vat_rate_id);