package com.jotoai.voenix.shop.domain.orders.assembler

import com.jotoai.voenix.shop.article.api.ArticleQueryService
import com.jotoai.voenix.shop.domain.orders.dto.AddressDto
import com.jotoai.voenix.shop.domain.orders.dto.OrderDto
import com.jotoai.voenix.shop.domain.orders.dto.OrderItemDto
import com.jotoai.voenix.shop.domain.orders.entity.Order
import com.jotoai.voenix.shop.domain.orders.entity.OrderItem
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Component

@Component
class OrderAssembler(
    @param:Value("\${app.base-url:http://localhost:8080}") private val appBaseUrl: String,
    private val articleQueryService: ArticleQueryService,
) {
    fun toDto(entity: Order): OrderDto =
        OrderDto(
            id = requireNotNull(entity.id) { "Order ID cannot be null when converting to DTO" },
            orderNumber = requireNotNull(entity.orderNumber) { "Order number should be generated by database" },
            customerEmail = entity.customerEmail,
            customerFirstName = entity.customerFirstName,
            customerLastName = entity.customerLastName,
            customerPhone = entity.customerPhone,
            shippingAddress = AddressDto.fromEntity(entity.shippingAddress),
            billingAddress = entity.billingAddress?.let { AddressDto.fromEntity(it) },
            subtotal = entity.subtotal,
            taxAmount = entity.taxAmount,
            shippingAmount = entity.shippingAmount,
            totalAmount = entity.totalAmount,
            status = entity.status,
            cartId = entity.cartId,
            notes = entity.notes,
            items =
                run {
                    val articleIds = entity.items.map { it.articleId }.distinct()
                    val variantIds = entity.items.map { it.variantId }.distinct()
                    val articlesById = articleQueryService.getArticlesByIds(articleIds)
                    val variantsById = articleQueryService.getMugVariantsByIds(variantIds)
                    entity.items.map { toItemDto(it, articlesById, variantsById) }
                },
            pdfUrl = generatePdfUrl(entity.id),
            createdAt = requireNotNull(entity.createdAt) { "Order createdAt cannot be null when converting to DTO" },
            updatedAt = requireNotNull(entity.updatedAt) { "Order updatedAt cannot be null when converting to DTO" },
        )

    fun toItemDto(
        entity: OrderItem,
        articlesById: Map<Long, com.jotoai.voenix.shop.article.api.dto.ArticleDto>,
        variantsById: Map<Long, com.jotoai.voenix.shop.article.api.dto.MugArticleVariantDto>,
    ): OrderItemDto =
        OrderItemDto(
            id = requireNotNull(entity.id) { "OrderItem ID cannot be null when converting to DTO" },
            article =
                articlesById[entity.articleId]
                    ?: throw IllegalStateException("Missing ArticleDto for id: ${entity.articleId}"),
            variant =
                variantsById[entity.variantId]
                    ?: throw IllegalStateException("Missing MugArticleVariantDto for id: ${entity.variantId}"),
            quantity = entity.quantity,
            pricePerItem = entity.pricePerItem,
            totalPrice = entity.totalPrice,
            generatedImageId = entity.generatedImageId,
            generatedImageFilename = entity.generatedImageFilename,
            promptId = entity.promptId,
            customData = entity.customData,
            createdAt = requireNotNull(entity.createdAt) { "OrderItem createdAt cannot be null when converting to DTO" },
        )

    private fun generatePdfUrl(orderId: java.util.UUID): String = "$appBaseUrl/api/user/orders/$orderId/pdf"
}
